# Generated by Django 3.2 on 2021-04-17 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='login',
            table='login',
        ),
    ]
