# Generated by Django 3.2 on 2021-04-17 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='patient',
            table='patient',
        ),
    ]
