# Generated by Django 3.2 on 2021-04-23 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0002_alter_rdv_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdv',
            name='soins',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
