# Generated by Django 3.2 on 2021-04-23 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0003_rdv_soins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdv',
            name='soins',
            field=models.CharField(max_length=150),
        ),
    ]
